backend:
  name: github
  branch: master

media_folder: "static/images/uploads"
public_folder: "images/uploads"

collections:
  - name: project
    label: Project
    folder: projects
    create: true
    fields:
      - {name: title, label: Title}
      - {name: thumb, label: Thumbnail, widget: image}
      - {name: body, label: Body, widget: markdown}
  - name: tutorial
    label: Tutorial
    folder: tutorials
    create: true
    fields :
      - {name: title, label: Title}
      - {name: description, label: Description, widget: text}
      - {name: thumb, label: Thumbnail, widget: image}
      - {name: body, label: Body, widget: markdown}