backend:
  name: github
  branch: master
  repo: AlekMabry/alekstutorials

media_folder: "static/images/uploads"
public_folder: "images/uploads"

collections:
  - name: settings
    label: Settings
    files:
      - label: Portfolio Page
        name: portfolio
        file: src/content/portfolio.yml
        fields:
          - {name: logo, label: Site Logo, widget: image}
          - {name: pfp, label: Profile Picture, widget: image}
          - {name: about, label: About Description, widget: text}
  - name: "project"
    label: "Project"
    folder: src/content/projects
    create: true
    fields:
      - {name: title, label: Title}
      - {name: slug, label: Slug, widget: text}
      - {name: thumb, label: Thumbnail, widget: image}
      - {name: body, label: Body, widget: markdown}
  - name: "tutorial"
    label: "Tutorial"
    folder: src/content/tutorials
    create: true
    fields :
      - {name: title, label: Title}
      - {name: description, label: Description, widget: text}
      - {name: thumb, label: Thumbnail, widget: image}
      - {name: body, label: Body, widget: markdown}